name = "ig3-meet"
main = ".open-next/worker.js"       # hoặc ".open-next/worker/index.js" tùy phiên bản adapter
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
